name: tests-auth
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
        working-directory: ./auth
      - name: Run tests
        run: npm run test:ci
        working-directory: ./auth